version: '3'
services:
  mongo:
    image: mongo:latest
    volumes:
      - ./data/db:/data/mongodb
    ports:
      - 27017:27017

  redis:
    image: redis:latest
    volumes:
      - ./data:/data/redis
    ports:
      - 6379:6379
